// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCCHYSbbBeterrlFg5auzO1HVn0YGLpwAI',
//     appId: '1:969792964779:web:46479a7e87b6e606f48fee',
//     messagingSenderId: '969792964779',
//     projectId: 'hackathon-gdsc',
//     authDomain: 'hackathon-gdsc.firebaseapp.com',
//     storageBucket: 'hackathon-gdsc.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBOKqmzkOiEXhcpzBEtyeKlIDMZPt6kHmc',
//     appId: '1:969792964779:android:929a7b8521a5aafaf48fee',
//     messagingSenderId: '969792964779',
//     projectId: 'hackathon-gdsc',
//     storageBucket: 'hackathon-gdsc.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCrzVGkobib5dpNZL2b84ccMVXcws9YMQ8',
//     appId: '1:969792964779:ios:8d524cbc6e2daaf5f48fee',
//     messagingSenderId: '969792964779',
//     projectId: 'hackathon-gdsc',
//     storageBucket: 'hackathon-gdsc.appspot.com',
//     iosBundleId: 'com.example.legalease',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCrzVGkobib5dpNZL2b84ccMVXcws9YMQ8',
//     appId: '1:969792964779:ios:cbd033e9e4391375f48fee',
//     messagingSenderId: '969792964779',
//     projectId: 'hackathon-gdsc',
//     storageBucket: 'hackathon-gdsc.appspot.com',
//     iosBundleId: 'com.example.legalease.RunnerTests',
//   );
// }
